name: Deploy to GitHub Pages
env:
  RELEASE_DIR: release
  PUBLISH_DIR: release/wwwroot
  CSPROJ_FILE: src/Aneejian.Games.ClickMatch.Client/Aneejian.Games.ClickMatch.Client.csproj
  INDEX_HTML: src/Aneejian.Games.ClickMatch.Client/wwwroot/index.html
  BASE_HREF: /ClickMatch/

on:
  workflow_dispatch:    
  push:
    branches: [master]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Rewrite base href
      uses: kannansuresh/ghaction-base-href-rewriter@v1.0.0
      with:
        html_path: ${{ env.INDEX_HTML }}
        base_href: ${{ env.BASE_HREF }}

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0

    - name: Publish .NET Core Project
      run: dotnet publish ${{ env.CSPROJ_FILE }} -c Release -o ${{ env.RELEASE_DIR }}

    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
      
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
